# Generated by Django 3.1.5 on 2021-01-16 13:53

from django.db import migrations
import publications.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_content_fileimage_filetext_filevideo_onlyfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=publications.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=publications.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
