# Generated by Django 3.1.5 on 2021-02-01 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_auto_20210116_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileimage',
            old_name='file',
            new_name='image',
        ),
    ]
